name: OpenTwitterAPI
targets:
  OpenTwitterAPI:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [OpenTwitterAPI]
    info:
      path: ./Info.plist
      version: 2.45
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
