//
// AnimatedGifAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnimatedGifAllOf: Codable, JSONEncodable, Hashable {

    public var previewImageUrl: String?
    /** An array of all available variants of the media. */
    public var variants: [Variant]?

    public init(previewImageUrl: String? = nil, variants: [Variant]? = nil) {
        self.previewImageUrl = previewImageUrl
        self.variants = variants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case previewImageUrl = "preview_image_url"
        case variants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(previewImageUrl, forKey: .previewImageUrl)
        try container.encodeIfPresent(variants, forKey: .variants)
    }
}

