//
// EntityIndicesInclusiveInclusive.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represent a boundary range (start and end index) for a recognized entity (for example a hashtag or a mention). &#x60;start&#x60; must be smaller than &#x60;end&#x60;.  The start index is inclusive, the end index is inclusive. */
public struct EntityIndicesInclusiveInclusive: Codable, JSONEncodable, Hashable {

    /** Index (zero-based) at which position this entity ends.  The index is inclusive. */
    public var end: Int
    /** Index (zero-based) at which position this entity starts.  The index is inclusive. */
    public var start: Int

    public init(end: Int, start: Int) {
        self.end = end
        self.start = start
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case end
        case start
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(end, forKey: .end)
        try container.encode(start, forKey: .start)
    }
}

