//
// Media.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Media: Codable, JSONEncodable, Hashable {

    /** The height of the media in pixels. */
    public var height: Int?
    /** The Media Key identifier for this attachment. */
    public var mediaKey: String?
    public var type: String
    /** The width of the media in pixels. */
    public var width: Int?

    public init(height: Int? = nil, mediaKey: String? = nil, type: String, width: Int? = nil) {
        self.height = height
        self.mediaKey = mediaKey
        self.type = type
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case height
        case mediaKey = "media_key"
        case type
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(mediaKey, forKey: .mediaKey)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

