//
// PhotoAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PhotoAllOf: Codable, JSONEncodable, Hashable {

    public var altText: String?
    public var url: String?

    public init(altText: String? = nil, url: String? = nil) {
        self.altText = altText
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case altText = "alt_text"
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(altText, forKey: .altText)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

