//
// UsersFollowingCreateResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersFollowingCreateResponseData: Codable, JSONEncodable, Hashable {

    public var following: Bool?
    public var pendingFollow: Bool?

    public init(following: Bool? = nil, pendingFollow: Bool? = nil) {
        self.following = following
        self.pendingFollow = pendingFollow
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case following
        case pendingFollow = "pending_follow"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(following, forKey: .following)
        try container.encodeIfPresent(pendingFollow, forKey: .pendingFollow)
    }
}

