version: '3.7'

# I use docker as a package manager and script executor rather than using homebrew or bundler.
services:
  open-twitter-api-gen:
    image: openapitools/openapi-generator-cli:v6.0.0
    working_dir: /open-twitter-api-gen
    volumes:
      - ./:/open-twitter-api-gen
    command: > # In docker-compose.yml, a multiline command should start with >.
      generate
      -i https://api.twitter.com/2/openapi.json
      -g swift5 
      -o /open-twitter-api-gen/Client
      --additional-properties=responseAs=AsyncAwait,projectName=OpenTwitterAPI,swiftPackagePath=Client/OpenTwitterAPI/Classes,podAuthors=yosshi4486,podSource=Client/OpenTwitterAPI/Classes,podLicense=MIT,podHomepage=https://github.com/yosshi4486/OpenTwitterAPI-for-Swift,podVersion=1.0.0