//
// ComplianceJob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComplianceJob: Codable, JSONEncodable {

    /** Creation time of the compliance job. */
    public var createdAt: Date
    /** Expiration time of the download URL. */
    public var downloadExpiresAt: Date
    /** URL from which the user will retrieve their compliance results. */
    public var downloadUrl: String
    /** Compliance Job ID. */
    public var id: String
    /** User-provided name for a compliance job. */
    public var name: String?
    public var status: ComplianceJobStatus
    public var type: ComplianceJobType
    /** Expiration time of the upload URL. */
    public var uploadExpiresAt: Date
    /** URL to which the user will upload their Tweet or user IDs. */
    public var uploadUrl: String

    public init(createdAt: Date, downloadExpiresAt: Date, downloadUrl: String, id: String, name: String? = nil, status: ComplianceJobStatus, type: ComplianceJobType, uploadExpiresAt: Date, uploadUrl: String) {
        self.createdAt = createdAt
        self.downloadExpiresAt = downloadExpiresAt
        self.downloadUrl = downloadUrl
        self.id = id
        self.name = name
        self.status = status
        self.type = type
        self.uploadExpiresAt = uploadExpiresAt
        self.uploadUrl = uploadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case downloadExpiresAt = "download_expires_at"
        case downloadUrl = "download_url"
        case id
        case name
        case status
        case type
        case uploadExpiresAt = "upload_expires_at"
        case uploadUrl = "upload_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(downloadExpiresAt, forKey: .downloadExpiresAt)
        try container.encode(downloadUrl, forKey: .downloadUrl)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(status, forKey: .status)
        try container.encode(type, forKey: .type)
        try container.encode(uploadExpiresAt, forKey: .uploadExpiresAt)
        try container.encode(uploadUrl, forKey: .uploadUrl)
    }
}

