//
// ComplianceJobType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Type of compliance job to list. */
public enum ComplianceJobType: String, Codable, CaseIterable {
    case tweets = "tweets"
    case users = "users"
}
