//
// FieldUnauthorizedProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FieldUnauthorizedProblemAllOf: Codable, JSONEncodable {

    public enum ResourceType: String, Codable, CaseIterable {
        case user = "user"
        case tweet = "tweet"
        case media = "media"
        case list = "list"
        case space = "space"
    }
    public enum Section: String, Codable, CaseIterable {
        case data = "data"
        case includes = "includes"
    }
    public var field: String
    public var resourceType: ResourceType
    public var section: Section

    public init(field: String, resourceType: ResourceType, section: Section) {
        self.field = field
        self.resourceType = resourceType
        self.section = section
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
        case resourceType = "resource_type"
        case section
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(field, forKey: .field)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(section, forKey: .section)
    }
}

