//
// Get2ComplianceJobsResponseMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Get2ComplianceJobsResponseMeta: Codable, JSONEncodable {

    /** The number of results returned in this response. */
    public var resultCount: Int?

    public init(resultCount: Int? = nil) {
        self.resultCount = resultCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resultCount = "result_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resultCount, forKey: .resultCount)
    }
}

