//
// Get2UsersIdMentionsResponseMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Get2UsersIdMentionsResponseMeta: Codable, JSONEncodable {

    /** The newest id in this response. */
    public var newestId: String?
    /** The next token. */
    public var nextToken: String?
    /** The oldest id in this response. */
    public var oldestId: String?
    /** The previous token. */
    public var previousToken: String?
    /** The number of results returned in this response. */
    public var resultCount: Int?

    public init(newestId: String? = nil, nextToken: String? = nil, oldestId: String? = nil, previousToken: String? = nil, resultCount: Int? = nil) {
        self.newestId = newestId
        self.nextToken = nextToken
        self.oldestId = oldestId
        self.previousToken = previousToken
        self.resultCount = resultCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newestId = "newest_id"
        case nextToken = "next_token"
        case oldestId = "oldest_id"
        case previousToken = "previous_token"
        case resultCount = "result_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(newestId, forKey: .newestId)
        try container.encodeIfPresent(nextToken, forKey: .nextToken)
        try container.encodeIfPresent(oldestId, forKey: .oldestId)
        try container.encodeIfPresent(previousToken, forKey: .previousToken)
        try container.encodeIfPresent(resultCount, forKey: .resultCount)
    }
}

