//
// InvalidRequestProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvalidRequestProblemAllOf: Codable, JSONEncodable {

    public var errors: [InvalidRequestProblemAllOfErrors]?

    public init(errors: [InvalidRequestProblemAllOfErrors]? = nil) {
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

