//
// MentionFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represent the portion of text recognized as a User mention, and its start and end position within the text. */
public struct MentionFields: Codable, JSONEncodable {

    /** Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    public var id: String
    /** The Twitter handle (screen name) of this user. */
    public var username: String

    public init(id: String, username: String) {
        self.id = id
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
    }
}

