//
// OperationalDisconnectProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OperationalDisconnectProblemAllOf: Codable, JSONEncodable {

    public enum DisconnectType: String, Codable, CaseIterable {
        case operationalDisconnect = "OperationalDisconnect"
        case upstreamOperationalDisconnect = "UpstreamOperationalDisconnect"
        case forceDisconnect = "ForceDisconnect"
        case upstreamUncleanDisconnect = "UpstreamUncleanDisconnect"
        case slowReader = "SlowReader"
        case internalError = "InternalError"
        case clientApplicationStateDegraded = "ClientApplicationStateDegraded"
        case invalidRules = "InvalidRules"
    }
    public var disconnectType: DisconnectType?

    public init(disconnectType: DisconnectType? = nil) {
        self.disconnectType = disconnectType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case disconnectType = "disconnect_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(disconnectType, forKey: .disconnectType)
    }
}

