//
// OperationalDisconnectProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** You have been disconnected for operational reasons. */
public struct OperationalDisconnectProblem: Codable, JSONEncodable {

    public enum DisconnectType: String, Codable, CaseIterable {
        case operationalDisconnect = "OperationalDisconnect"
        case upstreamOperationalDisconnect = "UpstreamOperationalDisconnect"
        case forceDisconnect = "ForceDisconnect"
        case upstreamUncleanDisconnect = "UpstreamUncleanDisconnect"
        case slowReader = "SlowReader"
        case internalError = "InternalError"
        case clientApplicationStateDegraded = "ClientApplicationStateDegraded"
        case invalidRules = "InvalidRules"
    }
    public var detail: String?
    public var status: Int?
    public var title: String
    public var type: String
    public var disconnectType: DisconnectType?

    public init(detail: String? = nil, status: Int? = nil, title: String, type: String, disconnectType: DisconnectType? = nil) {
        self.detail = detail
        self.status = status
        self.title = title
        self.type = type
        self.disconnectType = disconnectType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case detail
        case status
        case title
        case type
        case disconnectType = "disconnect_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(title, forKey: .title)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(disconnectType, forKey: .disconnectType)
    }
}

