//
// Poll.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represent a Poll attached to a Tweet. */
public struct Poll: Codable, JSONEncodable {

    public enum VotingStatus: String, Codable, CaseIterable {
        case _open = "open"
        case closed = "closed"
    }
    public var durationMinutes: Int?
    public var endDatetime: Date?
    /** Unique identifier of this poll. */
    public var id: String
    public var options: [PollOption]
    public var votingStatus: VotingStatus?

    public init(durationMinutes: Int? = nil, endDatetime: Date? = nil, id: String, options: [PollOption], votingStatus: VotingStatus? = nil) {
        self.durationMinutes = durationMinutes
        self.endDatetime = endDatetime
        self.id = id
        self.options = options
        self.votingStatus = votingStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case durationMinutes = "duration_minutes"
        case endDatetime = "end_datetime"
        case id
        case options
        case votingStatus = "voting_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(durationMinutes, forKey: .durationMinutes)
        try container.encodeIfPresent(endDatetime, forKey: .endDatetime)
        try container.encode(id, forKey: .id)
        try container.encode(options, forKey: .options)
        try container.encodeIfPresent(votingStatus, forKey: .votingStatus)
    }
}

