//
// ResourceNotFoundProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResourceNotFoundProblemAllOf: Codable, JSONEncodable {

    public enum ResourceType: String, Codable, CaseIterable {
        case user = "user"
        case tweet = "tweet"
        case media = "media"
        case list = "list"
        case space = "space"
    }
    public var parameter: String
    public var resourceId: String
    public var resourceType: ResourceType
    /** Value will match the schema of the field. */
    public var value: String

    public init(parameter: String, resourceId: String, resourceType: ResourceType, value: String) {
        self.parameter = parameter
        self.resourceId = resourceId
        self.resourceType = resourceType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parameter
        case resourceId = "resource_id"
        case resourceType = "resource_type"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(parameter, forKey: .parameter)
        try container.encode(resourceId, forKey: .resourceId)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(value, forKey: .value)
    }
}

