//
// RulesRequestSummaryOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A summary of the results of the addition of user-specified stream filtering rules. */
public struct RulesRequestSummaryOneOf: Codable, JSONEncodable {

    /** Number of user-specified stream filtering rules that were created. */
    public var created: Int
    /** Number of invalid user-specified stream filtering rules. */
    public var invalid: Int
    /** Number of user-specified stream filtering rules that were not created. */
    public var notCreated: Int
    /** Number of valid user-specified stream filtering rules. */
    public var valid: Int

    public init(created: Int, invalid: Int, notCreated: Int, valid: Int) {
        self.created = created
        self.invalid = invalid
        self.notCreated = notCreated
        self.valid = valid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case created
        case invalid
        case notCreated = "not_created"
        case valid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(created, forKey: .created)
        try container.encode(invalid, forKey: .invalid)
        try container.encode(notCreated, forKey: .notCreated)
        try container.encode(valid, forKey: .valid)
    }
}

