//
// TweetAttachments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies the type of attachments (if any) present in this Tweet. */
public struct TweetAttachments: Codable, JSONEncodable {

    /** A list of Media Keys for each one of the media attachments (if media are attached). */
    public var mediaKeys: [String]?
    /** A list of poll IDs (if polls are attached). */
    public var pollIds: [String]?

    public init(mediaKeys: [String]? = nil, pollIds: [String]? = nil) {
        self.mediaKeys = mediaKeys
        self.pollIds = pollIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaKeys = "media_keys"
        case pollIds = "poll_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mediaKeys, forKey: .mediaKeys)
        try container.encodeIfPresent(pollIds, forKey: .pollIds)
    }
}

