//
// UsersLikesCreateResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersLikesCreateResponseData: Codable, JSONEncodable {

    public var liked: Bool?

    public init(liked: Bool? = nil) {
        self.liked = liked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case liked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(liked, forKey: .liked)
    }
}

