//
// UserWithheld.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country). */
public struct UserWithheld: Codable, JSONEncodable {

    public enum Scope: String, Codable, CaseIterable {
        case user = "user"
    }
    /** Provides a list of countries where this content is not available. */
    public var countryCodes: Set<String>
    /** Indicates that the content being withheld is a `user`. */
    public var scope: Scope?

    public init(countryCodes: Set<String>, scope: Scope? = nil) {
        self.countryCodes = countryCodes
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case countryCodes = "country_codes"
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(countryCodes, forKey: .countryCodes)
        try container.encodeIfPresent(scope, forKey: .scope)
    }
}

