//
// UserPublicMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A list of metrics for this User. */
public struct UserPublicMetrics: Codable, JSONEncodable {

    /** Number of Users who are following this User. */
    public var followersCount: Int
    /** Number of Users this User is following. */
    public var followingCount: Int
    /** The number of lists that include this User. */
    public var listedCount: Int
    /** The number of Tweets (including Retweets) posted by this User. */
    public var tweetCount: Int

    public init(followersCount: Int, followingCount: Int, listedCount: Int, tweetCount: Int) {
        self.followersCount = followersCount
        self.followingCount = followingCount
        self.listedCount = listedCount
        self.tweetCount = tweetCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case followersCount = "followers_count"
        case followingCount = "following_count"
        case listedCount = "listed_count"
        case tweetCount = "tweet_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(followersCount, forKey: .followersCount)
        try container.encode(followingCount, forKey: .followingCount)
        try container.encode(listedCount, forKey: .listedCount)
        try container.encode(tweetCount, forKey: .tweetCount)
    }
}

