//
// Variant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Variant: Codable, JSONEncodable {

    /** The bit rate of the media. */
    public var bitRate: Int?
    /** The content type of the media. */
    public var contentType: String?
    /** The url to the media. */
    public var url: String?

    public init(bitRate: Int? = nil, contentType: String? = nil, url: String? = nil) {
        self.bitRate = bitRate
        self.contentType = contentType
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bitRate = "bit_rate"
        case contentType = "content_type"
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bitRate, forKey: .bitRate)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

