//
// AnimatedGif.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnimatedGif: Codable, JSONEncodable, Hashable {

    /** The height of the media in pixels. */
    public var height: Int?
    /** The Media Key identifier for this attachment. */
    public var mediaKey: String?
    public var type: String
    /** The width of the media in pixels. */
    public var width: Int?
    public var previewImageUrl: String?
    /** An array of all available variants of the media. */
    public var variants: [Variant]?

    public init(height: Int? = nil, mediaKey: String? = nil, type: String, width: Int? = nil, previewImageUrl: String? = nil, variants: [Variant]? = nil) {
        self.height = height
        self.mediaKey = mediaKey
        self.type = type
        self.width = width
        self.previewImageUrl = previewImageUrl
        self.variants = variants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case height
        case mediaKey = "media_key"
        case type
        case width
        case previewImageUrl = "preview_image_url"
        case variants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(mediaKey, forKey: .mediaKey)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(previewImageUrl, forKey: .previewImageUrl)
        try container.encodeIfPresent(variants, forKey: .variants)
    }
}

