//
// InvalidRequestProblemAllOfErrors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvalidRequestProblemAllOfErrors: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var parameters: [String: [String]]?

    public init(message: String? = nil, parameters: [String: [String]]? = nil) {
        self.message = message
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(parameters, forKey: .parameters)
    }
}

