//
// ListFollowedResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListFollowedResponseData: Codable, JSONEncodable, Hashable {

    public var following: Bool?

    public init(following: Bool? = nil) {
        self.following = following
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case following
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(following, forKey: .following)
    }
}

