//
// DuplicateRuleProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DuplicateRuleProblemAllOf: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var value: String?

    public init(id: String? = nil, value: String? = nil) {
        self.id = id
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

