//
// DuplicateRuleProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The rule you have submitted is a duplicate. */
public struct DuplicateRuleProblem: Codable, JSONEncodable, Hashable {

    public var detail: String?
    public var status: Int?
    public var title: String
    public var type: String
    public var id: String?
    public var value: String?

    public init(detail: String? = nil, status: Int? = nil, title: String, type: String, id: String? = nil, value: String? = nil) {
        self.detail = detail
        self.status = status
        self.title = title
        self.type = type
        self.id = id
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case detail
        case status
        case title
        case type
        case id
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(title, forKey: .title)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

