//
// FilteredStreamingTweetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A Tweet or error that can be returned by the streaming Tweet API. The values returned with a successful streamed Tweet includes the user provided rules that the Tweet matched. */
public struct FilteredStreamingTweetResponse: Codable, JSONEncodable, Hashable {

    public var data: Tweet?
    public var errors: [Problem]?
    public var includes: Expansions?
    /** The list of rules which matched the Tweet */
    public var matchingRules: [FilteredStreamingTweetResponseMatchingRulesInner]?

    public init(data: Tweet? = nil, errors: [Problem]? = nil, includes: Expansions? = nil, matchingRules: [FilteredStreamingTweetResponseMatchingRulesInner]? = nil) {
        self.data = data
        self.errors = errors
        self.includes = includes
        self.matchingRules = matchingRules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case errors
        case includes
        case matchingRules = "matching_rules"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(includes, forKey: .includes)
        try container.encodeIfPresent(matchingRules, forKey: .matchingRules)
    }
}

