//
// ReplySettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following. */
public enum ReplySettings: String, Codable, CaseIterable {
    case everyone = "everyone"
    case mentionedusers = "mentionedUsers"
    case following = "following"
    case other = "other"
}
