//
// RuleNoId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A user-provided stream filtering rule. */
public struct RuleNoId: Codable, JSONEncodable, Hashable {

    /** A tag meant for the labeling of user provided rules. */
    public var tag: String?
    /** The filterlang value of the rule. */
    public var value: String

    public init(tag: String? = nil, value: String) {
        self.tag = tag
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tag
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tag, forKey: .tag)
        try container.encode(value, forKey: .value)
    }
}

