//
// SpaceTopicsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Twitter Topic object. */
public struct SpaceTopicsInner: Codable, JSONEncodable, Hashable {

    /** The description of the given topic. */
    public var description: String?
    /** An ID suitable for use in the REST API. */
    public var id: String
    /** The name of the given topic. */
    public var name: String

    public init(description: String? = nil, id: String, name: String) {
        self.description = description
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case id
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}

