//
// UsersRetweetsCreateResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersRetweetsCreateResponseData: Codable, JSONEncodable, Hashable {

    public var retweeted: Bool?

    public init(retweeted: Bool? = nil) {
        self.retweeted = retweeted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case retweeted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(retweeted, forKey: .retweeted)
    }
}

