//
// AddOrDeleteRulesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AddOrDeleteRulesResponse: Codable {
    case typeAddRulesResponse(AddRulesResponse)
    case typeDeleteRulesResponse(DeleteRulesResponse)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAddRulesResponse(let value):
            try container.encode(value)
        case .typeDeleteRulesResponse(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AddRulesResponse.self) {
            self = .typeAddRulesResponse(value)
        } else if let value = try? container.decode(DeleteRulesResponse.self) {
            self = .typeDeleteRulesResponse(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of AddOrDeleteRulesResponse"))
        }
    }
}

