//
// AnimatedGifAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnimatedGifAllOf: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case animatedGif = "animated_gif"
    }
    public var type: ModelType?
    public var previewImageUrl: String?

    public init(type: ModelType? = nil, previewImageUrl: String? = nil) {
        self.type = type
        self.previewImageUrl = previewImageUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case previewImageUrl = "preview_image_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(previewImageUrl, forKey: .previewImageUrl)
    }
}

