//
// ClientForbiddenProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A problem that indicates your client is forbidden from making this request. */
public struct ClientForbiddenProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case httpsApiTwitterCom2ProblemsClientForbidden = "https://api.twitter.com/2/problems/client-forbidden"
    }
    public enum Reason: String, Codable, CaseIterable {
        case officialClientForbidden = "official-client-forbidden"
        case clientNotEnrolled = "client-not-enrolled"
    }
    public var title: String
    public var detail: String
    public var type: ModelType?
    public var reason: Reason?
    public var registrationUrl: String?

    public init(title: String, detail: String, type: ModelType? = nil, reason: Reason? = nil, registrationUrl: String? = nil) {
        self.title = title
        self.detail = detail
        self.type = type
        self.reason = reason
        self.registrationUrl = registrationUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case type
        case reason
        case registrationUrl = "registration_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(registrationUrl, forKey: .registrationUrl)
    }
}

