//
// CommonMediaFields.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommonMediaFields: Codable {

    /** The Media Key identifier for this attachment. */
    public var mediaKey: String?
    /** The height of the media in pixels */
    public var height: Int?
    /** The width of the media in pixels */
    public var width: Int?

    public init(mediaKey: String? = nil, height: Int? = nil, width: Int? = nil) {
        self.mediaKey = mediaKey
        self.height = height
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaKey = "media_key"
        case height
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mediaKey, forKey: .mediaKey)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

