//
// ComplianceJobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Status of a compliance job */
public enum ComplianceJobStatus: String, Codable, CaseIterable {
    case created = "created"
    case inProgress = "in_progress"
    case failed = "failed"
    case complete = "complete"
}
