//
// DeleteRulesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A response from deleting user-specified stream filtering rules. */
public struct DeleteRulesRequest: Codable {

    public var delete: DeleteRulesRequestDelete

    public init(delete: DeleteRulesRequestDelete) {
        self.delete = delete
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case delete
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(delete, forKey: .delete)
    }
}

