//
// DeleteRulesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeleteRulesResponse: Codable {

    public var meta: RulesResponseMetadata

    public init(meta: RulesResponseMetadata) {
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(meta, forKey: .meta)
    }
}

