//
// DisallowedResourceProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A problem that indicates that the resource requested violates the precepts of this API. */
public struct DisallowedResourceProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case httpsApiTwitterCom2ProblemsDisallowedResource = "https://api.twitter.com/2/problems/disallowed-resource"
    }
    public enum ResourceType: String, Codable, CaseIterable {
        case tweet = "tweet"
        case media = "media"
    }
    public enum Section: String, Codable, CaseIterable {
        case data = "data"
        case includes = "includes"
    }
    public var title: String
    public var detail: String
    public var type: ModelType?
    public var resourceId: String
    public var resourceType: ResourceType
    public var section: Section

    public init(title: String, detail: String, type: ModelType? = nil, resourceId: String, resourceType: ResourceType, section: Section) {
        self.title = title
        self.detail = detail
        self.type = type
        self.resourceId = resourceId
        self.resourceType = resourceType
        self.section = section
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case type
        case resourceId = "resource_id"
        case resourceType = "resource_type"
        case section
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(resourceId, forKey: .resourceId)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(section, forKey: .section)
    }
}

