//
// FieldUnauthorizedProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A problem that indicates that you are not allowed to see a particular field on a Tweet, User, etc. */
public struct FieldUnauthorizedProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case httpsApiTwitterCom2ProblemsNotAuthorizedForField = "https://api.twitter.com/2/problems/not-authorized-for-field"
    }
    public enum Section: String, Codable, CaseIterable {
        case data = "data"
        case includes = "includes"
    }
    public enum ResourceType: String, Codable, CaseIterable {
        case tweet = "tweet"
        case media = "media"
    }
    public var title: String
    public var detail: String
    public var type: ModelType?
    public var section: Section
    public var resourceType: ResourceType
    public var field: String

    public init(title: String, detail: String, type: ModelType? = nil, section: Section, resourceType: ResourceType, field: String) {
        self.title = title
        self.detail = detail
        self.type = type
        self.section = section
        self.resourceType = resourceType
        self.field = field
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case type
        case section
        case resourceType = "resource_type"
        case field
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(section, forKey: .section)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(field, forKey: .field)
    }
}

