//
// FilteredStreamingTweet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A tweet or error that can be returned by the streaming tweet API */
public enum FilteredStreamingTweet: Codable {
    case typeFilteredStreamingTweetOneOf(FilteredStreamingTweetOneOf)
    case typeStreamingTweetOneOf(StreamingTweetOneOf)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeFilteredStreamingTweetOneOf(let value):
            try container.encode(value)
        case .typeStreamingTweetOneOf(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(FilteredStreamingTweetOneOf.self) {
            self = .typeFilteredStreamingTweetOneOf(value)
        } else if let value = try? container.decode(StreamingTweetOneOf.self) {
            self = .typeStreamingTweetOneOf(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of FilteredStreamingTweet"))
        }
    }
}

