//
// FullTextEntities.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FullTextEntities: Codable {

    public var urls: [UrlEntity]?
    public var hashtags: [HashtagEntity]?
    public var mentions: [MentionEntity]?
    public var cashtags: [CashtagEntity]?

    public init(urls: [UrlEntity]? = nil, hashtags: [HashtagEntity]? = nil, mentions: [MentionEntity]? = nil, cashtags: [CashtagEntity]? = nil) {
        self.urls = urls
        self.hashtags = hashtags
        self.mentions = mentions
        self.cashtags = cashtags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urls
        case hashtags
        case mentions
        case cashtags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(urls, forKey: .urls)
        try container.encodeIfPresent(hashtags, forKey: .hashtags)
        try container.encodeIfPresent(mentions, forKey: .mentions)
        try container.encodeIfPresent(cashtags, forKey: .cashtags)
    }
}

