//
// GenericProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A generic problem with no additional information beyond that provided by the HTTP status code. */
public struct GenericProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case aboutBlank = "about:blank"
    }
    public var title: String
    public var detail: String
    public var type: ModelType?
    public var status: Int

    public init(title: String, detail: String, type: ModelType? = nil, status: Int) {
        self.title = title
        self.detail = detail
        self.type = type
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case type
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(status, forKey: .status)
    }
}

