//
// GenericProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenericProblemAllOf: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case aboutBlank = "about:blank"
    }
    public var type: ModelType?
    public var status: Int

    public init(type: ModelType? = nil, status: Int) {
        self.type = type
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(status, forKey: .status)
    }
}

