//
// InlineObject3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InlineObject3: Codable {

    public enum ReplySettings: String, Codable, CaseIterable {
        case following = "following"
        case mentionedusers = "mentionedUsers"
    }
    /** The content of the Tweet. */
    public var text: String?
    /** Link to take the conversation from the public timeline to a private Direct Message. */
    public var directMessageDeepLink: String?
    /** Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    public var quoteTweetId: String?
    /** Exclusive Tweet for super followers. */
    public var forSuperFollowersOnly: Bool?
    public var reply: Model2TweetsReply?
    public var media: Model2TweetsMedia?
    public var poll: Model2TweetsPoll?
    /** Settings to indicate who can reply to the Tweet. */
    public var replySettings: ReplySettings?
    public var geo: Model2TweetsGeo?

    public init(text: String? = nil, directMessageDeepLink: String? = nil, quoteTweetId: String? = nil, forSuperFollowersOnly: Bool? = nil, reply: Model2TweetsReply? = nil, media: Model2TweetsMedia? = nil, poll: Model2TweetsPoll? = nil, replySettings: ReplySettings? = nil, geo: Model2TweetsGeo? = nil) {
        self.text = text
        self.directMessageDeepLink = directMessageDeepLink
        self.quoteTweetId = quoteTweetId
        self.forSuperFollowersOnly = forSuperFollowersOnly
        self.reply = reply
        self.media = media
        self.poll = poll
        self.replySettings = replySettings
        self.geo = geo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case directMessageDeepLink = "direct_message_deep_link"
        case quoteTweetId = "quote_tweet_id"
        case forSuperFollowersOnly = "for_super_followers_only"
        case reply
        case media
        case poll
        case replySettings = "reply_settings"
        case geo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(directMessageDeepLink, forKey: .directMessageDeepLink)
        try container.encodeIfPresent(quoteTweetId, forKey: .quoteTweetId)
        try container.encodeIfPresent(forSuperFollowersOnly, forKey: .forSuperFollowersOnly)
        try container.encodeIfPresent(reply, forKey: .reply)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encodeIfPresent(poll, forKey: .poll)
        try container.encodeIfPresent(replySettings, forKey: .replySettings)
        try container.encodeIfPresent(geo, forKey: .geo)
    }
}

