//
// InlineObject5.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A request to create a new batch compliance job. */
public struct InlineObject5: Codable {

    public var type: ComplianceJobType
    /** If true, this endpoint will return a pre-signed URL with resumable uploads enabled */
    public var resumable: Bool?
    /** User-provided name for a compliance job */
    public var name: String?

    public init(type: ComplianceJobType, resumable: Bool? = nil, name: String? = nil) {
        self.type = type
        self.resumable = resumable
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case resumable
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(resumable, forKey: .resumable)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

