//
// InvalidRequestProblemAllOfErrors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvalidRequestProblemAllOfErrors: Codable {

    public var parameters: [String: [String]]?
    public var message: String?

    public init(parameters: [String: [String]]? = nil, message: String? = nil) {
        self.parameters = parameters
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parameters
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parameters, forKey: .parameters)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

