//
// ListLookupMultipleUsersLookupResponseMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListLookupMultipleUsersLookupResponseMeta: Codable {

    /** The previous token */
    public var previousToken: String?
    /** The next token */
    public var nextToken: String?
    /** The number of user results returned in this response */
    public var resultCount: Int?

    public init(previousToken: String? = nil, nextToken: String? = nil, resultCount: Int? = nil) {
        self.previousToken = previousToken
        self.nextToken = nextToken
        self.resultCount = resultCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case previousToken = "previous_token"
        case nextToken = "next_token"
        case resultCount = "result_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(previousToken, forKey: .previousToken)
        try container.encodeIfPresent(nextToken, forKey: .nextToken)
        try container.encodeIfPresent(resultCount, forKey: .resultCount)
    }
}

