//
// ListMemberResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListMemberResponseData: Codable {

    public var member: Bool?

    public init(member: Bool? = nil) {
        self.member = member
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case member
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(member, forKey: .member)
    }
}

