//
// Model2TweetsReply.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Tweet information of the Tweet being replied to. */
public struct Model2TweetsReply: Codable {

    /** Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    public var inReplyToTweetId: String?
    /** A list of User Ids to be excluded from the reply Tweet. */
    public var excludeReplyUserIds: [String]?

    public init(inReplyToTweetId: String? = nil, excludeReplyUserIds: [String]? = nil) {
        self.inReplyToTweetId = inReplyToTweetId
        self.excludeReplyUserIds = excludeReplyUserIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inReplyToTweetId = "in_reply_to_tweet_id"
        case excludeReplyUserIds = "exclude_reply_user_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inReplyToTweetId, forKey: .inReplyToTweetId)
        try container.encodeIfPresent(excludeReplyUserIds, forKey: .excludeReplyUserIds)
    }
}

