//
// OperationalDisconnectProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** You have been disconnected for operational reasons. */
public struct OperationalDisconnectProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case httpsApiTwitterCom2ProblemsOperationalDisconnect = "https://api.twitter.com/2/problems/operational-disconnect"
    }
    public enum DisconnectType: String, Codable, CaseIterable {
        case operationalDisconnect = "OperationalDisconnect"
        case upstreamOperationalDisconnect = "UpstreamOperationalDisconnect"
        case forceDisconnect = "ForceDisconnect"
        case upstreamUncleanDisconnect = "UpstreamUncleanDisconnect"
        case slowReader = "SlowReader"
        case internalError = "InternalError"
        case clientApplicationStateDegraded = "ClientApplicationStateDegraded"
        case invalidRules = "InvalidRules"
    }
    public var title: String
    public var detail: String
    public var type: ModelType?
    public var disconnectType: DisconnectType?

    public init(title: String, detail: String, type: ModelType? = nil, disconnectType: DisconnectType? = nil) {
        self.title = title
        self.detail = detail
        self.type = type
        self.disconnectType = disconnectType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case type
        case disconnectType = "disconnect_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(disconnectType, forKey: .disconnectType)
    }
}

