//
// Photo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Photo: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case photo = "photo"
    }
    /** The Media Key identifier for this attachment. */
    public var mediaKey: String?
    /** The height of the media in pixels */
    public var height: Int?
    /** The width of the media in pixels */
    public var width: Int?
    public var type: ModelType?
    public var url: String?
    public var altText: String?

    public init(mediaKey: String? = nil, height: Int? = nil, width: Int? = nil, type: ModelType? = nil, url: String? = nil, altText: String? = nil) {
        self.mediaKey = mediaKey
        self.height = height
        self.width = width
        self.type = type
        self.url = url
        self.altText = altText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaKey = "media_key"
        case height
        case width
        case type
        case url
        case altText = "alt_text"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mediaKey, forKey: .mediaKey)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(altText, forKey: .altText)
    }
}

