//
// PollOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Describes a choice in a Poll object. */
public struct PollOption: Codable {

    /** Position of this choice in the poll. */
    public var position: Int
    /** The text of a poll choice. */
    public var label: String
    /** Number of users who voted for this choice. */
    public var votes: Int

    public init(position: Int, label: String, votes: Int) {
        self.position = position
        self.label = label
        self.votes = votes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position
        case label
        case votes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(position, forKey: .position)
        try container.encode(label, forKey: .label)
        try container.encode(votes, forKey: .votes)
    }
}

