//
// ResourceUnavailableProblemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResourceUnavailableProblemAllOf: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case httpsApiTwitterCom2ProblemsResourceUnavailable = "https://api.twitter.com/2/problems/resource-unavailable"
    }
    public enum ResourceType: String, Codable, CaseIterable {
        case user = "user"
        case tweet = "tweet"
        case media = "media"
    }
    public var type: ModelType?
    public var parameter: String
    public var resourceId: String
    public var resourceType: ResourceType

    public init(type: ModelType? = nil, parameter: String, resourceId: String, resourceType: ResourceType) {
        self.type = type
        self.parameter = parameter
        self.resourceId = resourceId
        self.resourceType = resourceType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case parameter
        case resourceId = "resource_id"
        case resourceType = "resource_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(parameter, forKey: .parameter)
        try container.encode(resourceId, forKey: .resourceId)
        try container.encode(resourceType, forKey: .resourceType)
    }
}

