//
// RulesResponseMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RulesResponseMetadata: Codable {

    public var sent: String
    public var summary: RulesRequestSummary?

    public init(sent: String, summary: RulesRequestSummary? = nil) {
        self.sent = sent
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sent
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sent, forKey: .sent)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

