//
// RuleNoId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A user-provided stream filtering rule. */
public struct RuleNoId: Codable {

    /** The filterlang value of the rule. */
    public var value: String
    /** A tag meant for the labeling of user provided rules. */
    public var tag: String?

    public init(value: String, tag: String? = nil) {
        self.value = value
        self.tag = tag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case tag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(tag, forKey: .tag)
    }
}

