//
// SingleUserLookupResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SingleUserLookupResponse: Codable {

    public var data: User?
    public var includes: Expansions?
    public var errors: [Problem]?

    public init(data: User? = nil, includes: Expansions? = nil, errors: [Problem]? = nil) {
        self.data = data
        self.includes = includes
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case includes
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(includes, forKey: .includes)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

