//
// TweetPromotedMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Promoted nonpublic engagement metrics for the Tweet at the time of the request. */
public struct TweetPromotedMetrics: Codable {

    /** Number of times this Tweet has been viewed. */
    public var impressionCount: Int?
    /** Number of times this Tweet has been liked. */
    public var likeCount: Int?
    /** Number of times this Tweet has been replied to. */
    public var replyCount: Int?
    /** Number of times this Tweet has been Retweeted. */
    public var retweetCount: Int?

    public init(impressionCount: Int? = nil, likeCount: Int? = nil, replyCount: Int? = nil, retweetCount: Int? = nil) {
        self.impressionCount = impressionCount
        self.likeCount = likeCount
        self.replyCount = replyCount
        self.retweetCount = retweetCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case impressionCount = "impression_count"
        case likeCount = "like_count"
        case replyCount = "reply_count"
        case retweetCount = "retweet_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(impressionCount, forKey: .impressionCount)
        try container.encodeIfPresent(likeCount, forKey: .likeCount)
        try container.encodeIfPresent(replyCount, forKey: .replyCount)
        try container.encodeIfPresent(retweetCount, forKey: .retweetCount)
    }
}

