//
// TweetOrganicMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Organic nonpublic engagement metrics for the Tweet at the time of the request. */
public struct TweetOrganicMetrics: Codable {

    /** Number of times this Tweet has been viewed. */
    public var impressionCount: Int
    /** Number of times this Tweet has been Retweeted. */
    public var retweetCount: Int
    /** Number of times this Tweet has been replied to. */
    public var replyCount: Int
    /** Number of times this Tweet has been liked. */
    public var likeCount: Int

    public init(impressionCount: Int, retweetCount: Int, replyCount: Int, likeCount: Int) {
        self.impressionCount = impressionCount
        self.retweetCount = retweetCount
        self.replyCount = replyCount
        self.likeCount = likeCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case impressionCount = "impression_count"
        case retweetCount = "retweet_count"
        case replyCount = "reply_count"
        case likeCount = "like_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(impressionCount, forKey: .impressionCount)
        try container.encode(retweetCount, forKey: .retweetCount)
        try container.encode(replyCount, forKey: .replyCount)
        try container.encode(likeCount, forKey: .likeCount)
    }
}

