//
// TweetPublicMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Engagement metrics for the Tweet at the time of the request. */
public struct TweetPublicMetrics: Codable {

    /** Number of times this Tweet has been Retweeted. */
    public var retweetCount: Int
    /** Number of times this Tweet has been replied to. */
    public var replyCount: Int
    /** Number of times this Tweet has been liked. */
    public var likeCount: Int
    /** Number of times this Tweet has been quoted. */
    public var quoteCount: Int?

    public init(retweetCount: Int, replyCount: Int, likeCount: Int, quoteCount: Int? = nil) {
        self.retweetCount = retweetCount
        self.replyCount = replyCount
        self.likeCount = likeCount
        self.quoteCount = quoteCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case retweetCount = "retweet_count"
        case replyCount = "reply_count"
        case likeCount = "like_count"
        case quoteCount = "quote_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(retweetCount, forKey: .retweetCount)
        try container.encode(replyCount, forKey: .replyCount)
        try container.encode(likeCount, forKey: .likeCount)
        try container.encodeIfPresent(quoteCount, forKey: .quoteCount)
    }
}

