//
// UsageCapExceededProblem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A problem that indicates that a usage cap has been exceeded. */
public struct UsageCapExceededProblem: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case httpsApiTwitterCom2ProblemsUsageCapped = "https://api.twitter.com/2/problems/usage-capped"
    }
    public enum Period: String, Codable, CaseIterable {
        case daily = "Daily"
        case monthly = "Monthly"
    }
    public enum Scope: String, Codable, CaseIterable {
        case account = "Account"
        case product = "Product"
    }
    public var title: String
    public var detail: String
    public var type: ModelType?
    public var period: Period?
    public var scope: Scope?

    public init(title: String, detail: String, type: ModelType? = nil, period: Period? = nil, scope: Scope? = nil) {
        self.title = title
        self.detail = detail
        self.type = type
        self.period = period
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case detail
        case type
        case period
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(period, forKey: .period)
        try container.encodeIfPresent(scope, forKey: .scope)
    }
}

