//
// VideoAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoAllOf: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case video = "video"
    }
    public var type: ModelType?
    public var previewImageUrl: String?
    public var durationMs: Int?
    public var publicMetrics: VideoAllOfPublicMetrics?
    public var nonPublicMetrics: VideoAllOfNonPublicMetrics?
    public var organicMetrics: VideoAllOfOrganicMetrics?
    public var promotedMetrics: VideoAllOfPromotedMetrics?

    public init(type: ModelType? = nil, previewImageUrl: String? = nil, durationMs: Int? = nil, publicMetrics: VideoAllOfPublicMetrics? = nil, nonPublicMetrics: VideoAllOfNonPublicMetrics? = nil, organicMetrics: VideoAllOfOrganicMetrics? = nil, promotedMetrics: VideoAllOfPromotedMetrics? = nil) {
        self.type = type
        self.previewImageUrl = previewImageUrl
        self.durationMs = durationMs
        self.publicMetrics = publicMetrics
        self.nonPublicMetrics = nonPublicMetrics
        self.organicMetrics = organicMetrics
        self.promotedMetrics = promotedMetrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case previewImageUrl = "preview_image_url"
        case durationMs = "duration_ms"
        case publicMetrics = "public_metrics"
        case nonPublicMetrics = "non_public_metrics"
        case organicMetrics = "organic_metrics"
        case promotedMetrics = "promoted_metrics"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(previewImageUrl, forKey: .previewImageUrl)
        try container.encodeIfPresent(durationMs, forKey: .durationMs)
        try container.encodeIfPresent(publicMetrics, forKey: .publicMetrics)
        try container.encodeIfPresent(nonPublicMetrics, forKey: .nonPublicMetrics)
        try container.encodeIfPresent(organicMetrics, forKey: .organicMetrics)
        try container.encodeIfPresent(promotedMetrics, forKey: .promotedMetrics)
    }
}

