//
// Get2TweetsCountsAllResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Get2TweetsCountsAllResponse: Codable, JSONEncodable, Hashable {

    public var data: [SearchCount]?
    public var errors: [Problem]?
    public var meta: Get2TweetsCountsAllResponseMeta?

    public init(data: [SearchCount]? = nil, errors: [Problem]? = nil, meta: Get2TweetsCountsAllResponseMeta? = nil) {
        self.data = data
        self.errors = errors
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case errors
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}

