name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

# OpenTwitterAPI doesn't have a test target, we only check for building the source.
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
